
package sanfranciscoasis;

import database.ConexionDB;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;

public class Login extends javax.swing.JFrame {

    
    public Login() {
        initComponents();
         this.setLocationRelativeTo(null);
         this.setSize(1150,790);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        titulocontra = new javax.swing.JLabel();
        titulousuario = new javax.swing.JLabel();
        LoginUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        loginPassword = new javax.swing.JPasswordField();
        INICIARSESION = new javax.swing.JButton();
        Volverpantprincipal1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 147, 224));

        jLabel2.setFont(new java.awt.Font("Roboto SemiCondensed ExtraBold", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("COLEGIO SAN FRANCISCO DE ASÍS I.E.D");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 0, 1000, 170));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel1.setText("INICIAR SESIÓN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 227, -1, -1));

        titulocontra.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        titulocontra.setText("CONTRASEÑA");
        jPanel1.add(titulocontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 477, -1, -1));

        titulousuario.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        titulousuario.setText("USUARIO");
        jPanel1.add(titulousuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 325, -1, -1));

        LoginUsuario.setForeground(new java.awt.Color(102, 102, 102));
        LoginUsuario.setBorder(null);
        LoginUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        LoginUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(LoginUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 380, 808, 40));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 418, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 418, 10));

        loginPassword.setForeground(new java.awt.Color(102, 102, 102));
        loginPassword.setBorder(null);
        loginPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(loginPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 420, -1));

        INICIARSESION.setBackground(new java.awt.Color(0, 147, 224));
        INICIARSESION.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        INICIARSESION.setForeground(new java.awt.Color(255, 255, 255));
        INICIARSESION.setText("INICIAR SESIÓN");
        INICIARSESION.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        INICIARSESION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INICIARSESIONActionPerformed(evt);
            }
        });
        jPanel1.add(INICIARSESION, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 660, 180, 50));

        Volverpantprincipal1.setBackground(new java.awt.Color(0, 147, 224));
        Volverpantprincipal1.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        Volverpantprincipal1.setForeground(new java.awt.Color(255, 255, 255));
        Volverpantprincipal1.setText("ATRAS");
        Volverpantprincipal1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Volverpantprincipal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volverpantprincipal1ActionPerformed(evt);
            }
        });
        jPanel1.add(Volverpantprincipal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, 130, 50));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1160, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 170, 1160, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginPasswordActionPerformed
                              

    }//GEN-LAST:event_loginPasswordActionPerformed

    private void INICIARSESIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INICIARSESIONActionPerformed
                                                      
    String nombre = LoginUsuario.getText();
    String contraseña = new String(loginPassword.getPassword());

    String query = "SELECT tipo FROM usuarios WHERE nombre = ? AND contrasena = ?";

    try (Connection con = ConexionDB.conectar(); 
         PreparedStatement pst = con.prepareStatement(query)) {

        pst.setString(1, nombre);
        pst.setString(2, contraseña);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            String tipoUsuario = rs.getString("tipo");

            if ("profesor".equalsIgnoreCase(tipoUsuario)) {
                JOptionPane.showMessageDialog(this, "Bienvenido, Profesor");
                VistaProfesor profesorVista = new VistaProfesor();
                profesorVista.setVisible(true);
                this.dispose();  // Cierra la ventana actual
            } else if ("estudiante".equalsIgnoreCase(tipoUsuario)) {
                JOptionPane.showMessageDialog(this, "Bienvenido, Estudiante");
                VistaEstudiante estudianteVista = new VistaEstudiante();
                estudianteVista.setVisible(true);
                this.dispose();  // Cierra la ventana actual
            } else {
                JOptionPane.showMessageDialog(this, "Tipo de usuario desconocido", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al conectar con la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_INICIARSESIONActionPerformed

    private void Volverpantprincipal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volverpantprincipal1ActionPerformed
       PantallaPrincipal p1 = new PantallaPrincipal();
        p1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Volverpantprincipal1ActionPerformed

    private void LoginUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton INICIARSESION;
    private javax.swing.JTextField LoginUsuario;
    private javax.swing.JButton Volverpantprincipal1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField loginPassword;
    private javax.swing.JLabel titulocontra;
    private javax.swing.JLabel titulousuario;
    // End of variables declaration//GEN-END:variables
}
